### ISSUE TITLE
store campaign file in expanded form inside hpcbench directory

### ISSUE THREAD

**Issue by ohm314** [BlueBrain/hpcbench#220]
This would be better for reproducibility, because it allows us to check after the fact that environment in which we ran hpcbench rather than trying to deduce it.

**Comment by tristan0x** [comment]
`campaign.yaml` is kept untouched so that `ben-merge` is able to detect that all given paths belong to the same campaign. I suggest we keep it that way and write another `campaign.expanded.yaml` file in the report top directory.
Would that suit your needs @ohm314 ?

**Comment by tristan0x** [comment]
ping @ohm314

**Comment by ohm314** [comment]
ok, as long ben-elastic and friends can use campaign.expanded.yaml instead this seems like a reasonable proposition
